/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LoginImport } from './routes/login'
import { Route as ManageImport } from './routes/_manage'
import { Route as ManageCourseImport } from './routes/_manage/course'

// Create/Update Routes

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const ManageRoute = ManageImport.update({
  id: '/_manage',
  getParentRoute: () => rootRoute,
} as any)

const ManageCourseRoute = ManageCourseImport.update({
  id: '/course',
  path: '/course',
  getParentRoute: () => ManageRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_manage': {
      id: '/_manage'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ManageImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/_manage/course': {
      id: '/_manage/course'
      path: '/course'
      fullPath: '/course'
      preLoaderRoute: typeof ManageCourseImport
      parentRoute: typeof ManageImport
    }
  }
}

// Create and export the route tree

interface ManageRouteChildren {
  ManageCourseRoute: typeof ManageCourseRoute
}

const ManageRouteChildren: ManageRouteChildren = {
  ManageCourseRoute: ManageCourseRoute,
}

const ManageRouteWithChildren =
  ManageRoute._addFileChildren(ManageRouteChildren)

export interface FileRoutesByFullPath {
  '': typeof ManageRouteWithChildren
  '/login': typeof LoginRoute
  '/course': typeof ManageCourseRoute
}

export interface FileRoutesByTo {
  '': typeof ManageRouteWithChildren
  '/login': typeof LoginRoute
  '/course': typeof ManageCourseRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_manage': typeof ManageRouteWithChildren
  '/login': typeof LoginRoute
  '/_manage/course': typeof ManageCourseRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '' | '/login' | '/course'
  fileRoutesByTo: FileRoutesByTo
  to: '' | '/login' | '/course'
  id: '__root__' | '/_manage' | '/login' | '/_manage/course'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  ManageRoute: typeof ManageRouteWithChildren
  LoginRoute: typeof LoginRoute
}

const rootRouteChildren: RootRouteChildren = {
  ManageRoute: ManageRouteWithChildren,
  LoginRoute: LoginRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_manage",
        "/login"
      ]
    },
    "/_manage": {
      "filePath": "_manage.tsx",
      "children": [
        "/_manage/course"
      ]
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/_manage/course": {
      "filePath": "_manage/course.tsx",
      "parent": "/_manage"
    }
  }
}
ROUTE_MANIFEST_END */
