services:
  # 定义 PostgreSQL 服务
  postgres:
    image: postgres:15 # 推荐指定一个具体的版本，例如 15
    container_name: postgres_dev # 给容器一个易于识别的名字
    restart: unless-stopped # 容器退出时自动重启，除非手动停止
    environment:
      # 使用环境变量设置数据库凭证和名称
      # 强烈建议使用 .env 文件来管理这些敏感信息
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '${POSTGRES_PORT}:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    # 可选：健康检查，确保数据库准备就绪
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-myapp}',
        ]
      interval: 10s # 每10秒检查一次
      timeout: 5s # 每次检查超时时间5秒
      retries: 5 # 重试5次失败后标记为不健康

  redis:
    image: redis:7
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

volumes:
  postgres_data:
  redis_data:
