services:
  # 定义 PostgreSQL 服务
  postgres:
    image: postgres:15 # 推荐指定一个具体的版本，例如 15
    container_name: postgres_dev # 给容器一个易于识别的名字
    restart: unless-stopped # 容器退出时自动重启，除非手动停止
    environment:
      # 使用环境变量设置数据库凭证和名称
      # 强烈建议使用 .env 文件来管理这些敏感信息
      POSTGRES_USER: ${POSTGRES_USER:-postgres} # 从 .env 文件读取，如果未设置则默认为 postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme} # 从 .env 文件读取，如果未设置则默认为 changeme (请务必修改!)
      POSTGRES_DB: ${POSTGRES_DB:-myapp} # 从 .env 文件读取，如果未设置则默认为 myapp
    ports:
      # 将宿主机的端口映射到容器的端口
      # 格式: "HOST_PORT:CONTAINER_PORT"
      # ${POSTGRES_PORT:-5432} 从 .env 文件读取宿主机端口，默认为 5432
      - '${POSTGRES_PORT:-5432}:5432'
    volumes:
      # 挂载一个命名的卷来持久化数据库数据
      # 这非常重要，否则容器停止或删除后数据会丢失
      - postgres_data:/var/lib/postgresql/data
    # 可选：健康检查，确保数据库准备就绪
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-myapp}',
        ]
      interval: 10s # 每10秒检查一次
      timeout: 5s # 每次检查超时时间5秒
      retries: 5 # 重试5次失败后标记为不健康

# 定义命名的卷
volumes:
  postgres_data:
    driver: local # 使用本地驱动程序
